"""adiciona anonimizacao_status em orthanc_references

Revision ID: 582dea7a0fa3
Revises: 5e12b4071d59
Create Date: 2026-07-19 18:36:50.585935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582dea7a0fa3'
down_revision: Union[str, None] = '5e12b4071d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orthanc_references', sa.Column('anonimizacao_status', sa.String(length=20), server_default=sa.text("'aguardando'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orthanc_references', 'anonimizacao_status')
    # ### end Alembic commands ###
