"""adiciona indice unico parcial contra revisao aberta duplicada

Revision ID: 5e12b4071d59
Revises: acf13f5ff44c
Create Date: 2026-07-17 02:52:09.907795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e12b4071d59'
down_revision: Union[str, None] = 'acf13f5ff44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_curation_reviews_aberta', 'curation_reviews', ['curation_id'], unique=True, postgresql_where=sa.text("status IN ('solicitada', 'respondida')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_curation_reviews_aberta', table_name='curation_reviews', postgresql_where=sa.text("status IN ('solicitada', 'respondida')"))
    # ### end Alembic commands ###
