"""cria tabelas de curadoria e auditoria

Revision ID: 9e7f46bd8b2d
Revises: f7f1895c6b21
Create Date: 2026-07-13 02:02:02.733668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7f46bd8b2d'
down_revision: Union[str, None] = 'f7f1895c6b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=15), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_acao'), 'audit_logs', ['acao'], unique=False)
    op.create_index(op.f('ix_audit_logs_criado_em'), 'audit_logs', ['criado_em'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.create_table('curations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orthanc_reference_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=False),
    sa.Column('tipo_radiografia', sa.String(length=30), nullable=True),
    sa.Column('dentes', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('idade_min', sa.Integer(), nullable=True),
    sa.Column('idade_max', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=15), nullable=True),
    sa.Column('achado_principal', sa.String(length=40), nullable=True),
    sa.Column('achados_detalhe', sa.Text(), nullable=True),
    sa.Column('qualidade_tecnica', sa.String(length=20), nullable=True),
    sa.Column('dificuldade', sa.String(length=20), nullable=True),
    sa.Column('descricao_didatica', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('finalidade', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('anonimizacao_validada', sa.Boolean(), nullable=False),
    sa.Column('curador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['orthanc_reference_id'], ['orthanc_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curations_curador_id'), 'curations', ['curador_id'], unique=False)
    op.create_index(op.f('ix_curations_id'), 'curations', ['id'], unique=False)
    op.create_index(op.f('ix_curations_orthanc_reference_id'), 'curations', ['orthanc_reference_id'], unique=False)
    op.create_index(op.f('ix_curations_status'), 'curations', ['status'], unique=False)
    op.create_table('curation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curation_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('status_anterior', sa.String(length=25), nullable=True),
    sa.Column('status_novo', sa.String(length=25), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['curation_id'], ['curations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_history_curation_id'), 'curation_history', ['curation_id'], unique=False)
    op.create_index(op.f('ix_curation_history_id'), 'curation_history', ['id'], unique=False)
    op.create_table('curation_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curation_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('primeiro_parecer', sa.Text(), nullable=True),
    sa.Column('revisor_id', sa.Integer(), nullable=True),
    sa.Column('parecer_revisor', sa.Text(), nullable=True),
    sa.Column('concordancia', sa.String(length=15), nullable=True),
    sa.Column('decisao_final', sa.String(length=25), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('respondido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curation_id'], ['curations.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curation_reviews_curation_id'), 'curation_reviews', ['curation_id'], unique=False)
    op.create_index(op.f('ix_curation_reviews_id'), 'curation_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curation_reviews_id'), table_name='curation_reviews')
    op.drop_index(op.f('ix_curation_reviews_curation_id'), table_name='curation_reviews')
    op.drop_table('curation_reviews')
    op.drop_index(op.f('ix_curation_history_id'), table_name='curation_history')
    op.drop_index(op.f('ix_curation_history_curation_id'), table_name='curation_history')
    op.drop_table('curation_history')
    op.drop_index(op.f('ix_curations_status'), table_name='curations')
    op.drop_index(op.f('ix_curations_orthanc_reference_id'), table_name='curations')
    op.drop_index(op.f('ix_curations_id'), table_name='curations')
    op.drop_index(op.f('ix_curations_curador_id'), table_name='curations')
    op.drop_table('curations')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_criado_em'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_acao'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
