"""adiciona origem em orthanc_references

Revision ID: a1b3c5d7e9f2
Revises: f4d7b1a9e2c6
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b3c5d7e9f2'
down_revision: Union[str, None] = 'f4d7b1a9e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='externa': registros ja existentes (gravados antes
    # desta coluna existir) ficam marcados como "externa" - a instancia que
    # guardamos e sempre a versao JA ANONIMIZADA, e o Orthanc nao preserva a
    # metadata de origem do original depois da anonimizacao, entao nao ha
    # como descobrir retroativamente se vieram por C-STORE (UFSC) ou upload
    # (externa). So imagens recebidas a PARTIR DE AGORA (ver
    # _determinar_origem em images_router.py) tem a origem detectada de
    # verdade a partir da metadata "Origin" do Orthanc.
    op.add_column(
        'orthanc_references',
        sa.Column('origem', sa.String(length=10), server_default=sa.text("'externa'"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orthanc_references', 'origem')
    # ### end Alembic commands ###
