"""adiciona ativo em orthanc_references

Revision ID: acf13f5ff44c
Revises: 9e7f46bd8b2d
Create Date: 2026-07-16 21:17:22.146209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf13f5ff44c'
down_revision: Union[str, None] = '9e7f46bd8b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orthanc_references', sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orthanc_references', 'ativo')
    # ### end Alembic commands ###
