"""remove finalidade de curations

Revision ID: b2d5e8a1c4f7
Revises: a1b3c5d7e9f2
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d5e8a1c4f7'
down_revision: Union[str, None] = 'a1b3c5d7e9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove por completo o campo "Finalidade" (Ensino/Pesquisa/Ambos) do
    # sistema, a pedido explicito do responsavel pelo projeto. Isso apaga
    # PERMANENTEMENTE esse dado para todas as fichas de curadoria ja
    # preenchidas - nao ha como recuperar depois. O campo tambem foi
    # removido da ficha de curadoria (backend/app/modules/curations.py),
    # dos filtros de Pesquisa avancada e da tela de Segunda opiniao.
    op.drop_column('curations', 'finalidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recria a coluna, mas os valores antigos NAO voltam (foram perdidos
    # no upgrade). Todas as fichas ficariam com finalidade em branco.
    op.add_column(
        'curations',
        sa.Column('finalidade', sa.String(length=15), nullable=True),
    )
    # ### end Alembic commands ###
