"""criar tabela orthanc_references

Revision ID: f7f1895c6b21
Revises: 4a8e39c8d753
Create Date: 2026-07-11 23:19:18.009211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f1895c6b21'
down_revision: Union[str, None] = '4a8e39c8d753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orthanc_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orthanc_id', sa.String(length=255), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('series_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('dicomweb_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orthanc_references_id'), 'orthanc_references', ['id'], unique=False)
    op.create_index(op.f('ix_orthanc_references_orthanc_id'), 'orthanc_references', ['orthanc_id'], unique=True)
    op.create_index(op.f('ix_orthanc_references_series_instance_uid'), 'orthanc_references', ['series_instance_uid'], unique=False)
    op.create_index(op.f('ix_orthanc_references_sop_instance_uid'), 'orthanc_references', ['sop_instance_uid'], unique=False)
    op.create_index(op.f('ix_orthanc_references_study_instance_uid'), 'orthanc_references', ['study_instance_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orthanc_references_study_instance_uid'), table_name='orthanc_references')
    op.drop_index(op.f('ix_orthanc_references_sop_instance_uid'), table_name='orthanc_references')
    op.drop_index(op.f('ix_orthanc_references_series_instance_uid'), table_name='orthanc_references')
    op.drop_index(op.f('ix_orthanc_references_orthanc_id'), table_name='orthanc_references')
    op.drop_index(op.f('ix_orthanc_references_id'), table_name='orthanc_references')
    op.drop_table('orthanc_references')
    # ### end Alembic commands ###
